export const callStates = {
  CALL_UNAVAILABLE: 'CALL_UNAVAILABLE',
  CALL_AVAILABLE: 'CALL_AVAILABLE',
  CALL_REQUESTED: 'CALL_REQUESTED',
  CALL_IN_PROGRESS: 'CALL_IN_PROGRESS',
}

export const CALL_SET_LOCAL_STREAM = 'CALL_SET_LOCAL_STREAM'
export const CALL_SET_CALL_STATE = 'CALL_SET_CALL_STATE'
export const CALL_SET_CALLING_DIALOGUE_VISIBLE =
  'CALL_SET_CALLING_DIALOGUE_VISIBLE'
export const CALL_SET_CALLER_USERNAME = 'CALL_SET_CALLER_USERNAME'
export const CALL_SET_CALL_REJECTED = 'CALL_SET_CALL_REJECTED'
